import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const heroes = [
            { id: 81, name: '1A211', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Aircraft Loadmaster Helper - Air Force - Enlisted - 1A211', civ: 'Aircraft Cargo Handling Supervisors', civDesc: 'Supervise and coordinate the activities of ground crew in the loading, unloading, securing, and staging of aircraft cargo or baggage. May determine the quantity and orientation of cargo and compute aircraft center of gravity. May accompany aircraft as member of flight crew and monitor and handle cargo in flight, and assist and brief passengers on safety and emergency procedures. Includes loadmasters.' },
            { id: 118, name: '1A651', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Flight Attendant Journeyman - Air Force - Enlisted - 1A651', civ: 'Flight Attendants', civDesc: 'Provide personal services to ensure the safety, security, and comfort of airline passengers during flight. Greet passengers, verify tickets, explain use of safety equipment, and serve food or beverages.' },
            { id: 150, name: '1A831F', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Airborne Cryptologic Language Analyst Apprentice, Arabic - Air Force - Enlisted - 1A831F', civ: 'Interpreters and Translators', civDesc: 'Interpret oral or sign language, or translate written text from one language into another.' },
            { id: 209, name: '1B034', Tag1: 'E', Tag2: 'F', Tag3: 'O', mocDesc: 'Computer Systems Programming Apprentice - Air Force - Enlisted - 1B034', civ: 'Computer Programmers', civDesc: 'Create, modify, and test the code, forms, and script that allow computer applications to run. Work from specifications drawn up by software developers or other individuals. May assist software developers by analyzing user needs and designing software solutions. May develop and write computer programs to store, locate, and retrieve specific documents, data, and information.' },
            { id: 270, name: '1C072', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Aviation Resource Management Craftsman - Air Force - Enlisted - 1C072', civ: 'Airfield Operations Specialists', civDesc: 'Ensure the safe takeoff and landing of commercial and military aircraft. Duties include coordination between air-traffic control and maintenance personnel; dispatching; using airfield landing and navigational aids; implementing airfield safety procedures; monitoring and maintaining flight records; and applying knowledge of weather information.' },
            { id: 325, name: '1C811', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Ground Radar Systems Helper - Air Force - Enlisted - 1C811', civ: 'Electrical and Electronics Repairers, Commercial and Industrial Equipment', civDesc: 'Repair, test, adjust, or install electronic equipment, such as industrial controls, transmitters, and antennas. Excludes "Avionics Technicians", "Electronic Equipment Installers and Repairers, Motor Vehicles", and "Electrical and Electronics Installers and Repairers, Transportation Equipment".' },
            { id: 351, name: '1N151', Tag1: 'E', Tag2: 'F', Tag3: 'O', mocDesc: 'Imagery Analysis Journeyman - Air Force - Enlisted - 1N151', civ: 'Cartographers and Photogrammetrists', civDesc: 'Collect, analyze, and interpret geographic information provided by geodetic surveys, aerial photographs, and satellite data. Research, study, and prepare maps and other spatial data in digital or graphic form for legal, social, political, educational, and design purposes. May work with Geographic Information Systems (GIS). May design and evaluate algorithms, data structures, and user interfaces for GIS and mapping systems.' },
            { id: 881, name: '1W031B', Tag1: 'E', Tag2: 'F', Tag3: 'O', mocDesc: 'Weather Apprentice, Battlefield Airman - Air Force - Enlisted - 1W031B', civ: 'Life, Physical, and Social Science Technicians, All Other', civDesc: 'All life, physical, and social science technicians not listed separately.' },
            { id: 1325, name: '2A511H', Tag1: 'E', Tag2: 'F', Tag3: 'O', mocDesc: 'Aerospace Maintenance Helper, KC-10/E-4 - Air Force - Enlisted - 2A511H', civ: 'Aircraft Mechanics and Service Technicians', civDesc: 'Diagnose, adjust, repair, or overhaul aircraft engines and assemblies, such as hydraulic and pneumatic systems. Includes helicopter and aircraft engine specialists. Excludes "Avionics Technician".' },
            { id: 1376, name: '2A552D', Tag1: 'E', Tag2: 'F', Tag3: 'A', mocDesc: 'Helicopter/Tiltrotor Aircraft Maintenance Journeyman, CV-22 - Air Force - Enlisted - 2A552D', civ: 'Aircraft Mechanics and Service Technicians', civDesc: 'Diagnose, adjust, repair, or overhaul aircraft engines and assemblies, such as hydraulic and pneumatic systems. Includes helicopter and aircraft engine specialists. Excludes "Avionics Technician".' }
        ];
        return { heroes };
    }
}